POST http://localhost:9090/register HTTP/1.1
content-Type: application/json

{
    "username": "yourUsername",
    "password": "yourPassword",
    "email": "yourEmail@example.com",
    "name": "yourName"
}

###

POST http://localhost:9090/login HTTP/1.1
content-Type: application/json

{
    "password": "yourPassword",
    "email": "yourEmail@example.com"
}

